import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const DeveloperName = process.env.DEVELOPER_NAME
const DeveloperEmail = process.env.DEVELOPER_EMAIL
const DeveloperPhone = process.env.DEVELOPER_PHONE
const DeveloperAddress = process.env.DEVELOPER_ADDRESS
const LinkdinUrl = process.env.LINKDIN_ADDRESS
const InstagramUrl = process.env.INSTAGRAM_ADDRESS

const DeveloperData = {
  DeveloperName,
  DeveloperEmail,
  DeveloperPhone,
  DeveloperAddress,
  LinkdinUrl,
  InstagramUrl
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout DeveloperInfo={DeveloperData}>
        
        {children}
        </Layout>
        </body>
    </html>
  );
}
